### PR TITLE
Frontend fixes

### PR DESCRIPTION
**Pull request by hallister**
* `Checkbox` and `Radio` are resized and support sizes via `transform: scale(n).
* `:focus` only applies to `Checkbox`, `Radio` and `NavItem` when focus is applied via keyboard.
* `NavItems` now "move" the underline when hovering.

### CODE REVIEW

**Comment by hallister** [comment]
Hold off on merging this for now, want to cover any issues that come up with the frontend without a new PR.

**Comment by thedrew12** [comment]
Can you fix that button prop issue with the children

**Comment by hallister** [comment]
Sure thing

**Comment by hallister** [comment]
This fixes the Radio double-click bug and the Button child types.

**Comment by hallister** [comment]
Hold off on merging, found a few bugs.

**Pull request merged**
